"""empty message

Revision ID: 0e363a1014d1
Revises: 584f1542525c
Create Date: 2025-01-14 21:00:01.176297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e363a1014d1'
down_revision = '584f1542525c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hasMessages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasMessages', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
