"""empty message

Revision ID: 153e10b8b2f7
Revises: e116ad5c5f19
Create Date: 2025-01-14 21:03:49.842517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153e10b8b2f7'
down_revision = 'e116ad5c5f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('hasMessages', sa.Boolean(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_column('hasMessages')
    pass
    # ### end Alembic commands ###
