"""empty message

Revision ID: 3cf24561cd8f
Revises: b9aa78930b13
Create Date: 2025-01-20 09:05:06.938705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf24561cd8f'
down_revision = 'b9aa78930b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_column('receivedMsgs')
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('receivedMsgs', sa.INTEGER(), nullable=True))
    pass
    # ### end Alembic commands ###
