"""empty message

Revision ID: bf16bd064461
Revises: de94f245778f
Create Date: 2025-01-20 14:15:48.149688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf16bd064461'
down_revision = 'de94f245778f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('receivedMsgs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receivedMsgs', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
