"""empty message

Revision ID: b9aa78930b13
Revises: f3c83673193a
Create Date: 2025-01-20 06:59:44.626283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9aa78930b13'
down_revision = 'f3c83673193a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receivedMsgs', sa.Integer(), nullable=True))
        batch_op.drop_column('hasMessages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasMessages', sa.INTEGER(), server_default=sa.text("'False'"), nullable=True))
        batch_op.drop_column('receivedMsgs')

    # ### end Alembic commands ###
