"""added ondelete=CASCADE to shortlist-id on comments model

Revision ID: 40c6951baff0
Revises: fd6aeb4a4ec8
Create Date: 2024-08-31 20:15:00.150201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c6951baff0'
down_revision = 'fd6aeb4a4ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ondelete-cascade-shortlist-fk-comments', 'shortlists', ['shortlist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('ondelete-cascade-shortlist-fk-comments', type_='foreignkey')
        # batch_op.create_foreign_key(None, 'shortlists', ['shortlist_id'], ['id'])

    # ### end Alembic commands ###
