"""empty message

Revision ID: 4e998c0ff8bc
Revises: 40c6951baff0
Create Date: 2025-01-03 08:49:37.754285

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e998c0ff8bc"
down_revision = "40c6951baff0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('hasMessages', sa.Boolean(), nullable=True, create_constraint=False))
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_column('hasMessages')
    pass

    # ### end Alembic commands ###
