"""adding unique constraint to all model pks

Revision ID: 5397c398e5ff
Revises: d8879fe259da
Create Date: 2024-08-31 17:04:22.934384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5397c398e5ff'
down_revision = 'd8879fe259da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-booking-id', ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-comment-id', ['id'])

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-connections-id', ['id'])

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-genres-id', ['id'])

    with op.batch_alter_table('industry_areas', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-industry-areas-id', ['id'])

    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-job-titles-id', ['id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-locations-id', ['id'])

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-referrals-id', ['id'])

    with op.batch_alter_table('shortlists', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-shortlists-id', ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-users-id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique-users-id', type_='unique')

    with op.batch_alter_table('shortlists', schema=None) as batch_op:
        batch_op.drop_constraint('unique-shortlists-id', type_='unique')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint('unique-referrals-id', type_='unique')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint('unique-locations-id', type_='unique')

    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.drop_constraint('unique-job-titles-id', type_='unique')

    with op.batch_alter_table('industry_areas', schema=None) as batch_op:
        batch_op.drop_constraint('unique-industry-areas-id', type_='unique')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_constraint('unique-genres-id', type_='unique')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_constraint('unique-connections-id', type_='unique')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('unique-comment-id', type_='unique')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('unique-booking-id', type_='unique')

    # ### end Alembic commands ###
