"""empty message

Revision ID: 5641b4195f58
Revises: 6f1c7d6a2d96
Create Date: 2025-01-14 21:07:02.348118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5641b4195f58'
down_revision = '6f1c7d6a2d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasMessages', sa.Boolean(), server_default='False'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hasMessages')

    # ### end Alembic commands ###
