"""empty message

Revision ID: 584f1542525c
Revises: 4e998c0ff8bc
Create Date: 2025-01-14 20:57:57.488076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584f1542525c'
down_revision = '4e998c0ff8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_users')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('_alembic_tmp_users',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    # sa.Column('username', sa.VARCHAR(length=40), nullable=False),
    # sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    # sa.Column('profile_img_url', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('createdAt', sa.DATETIME(), nullable=False),
    # sa.Column('updatedAt', sa.DATETIME(), nullable=False),
    # sa.Column('hasMessages', sa.BOOLEAN(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('id', name='unique-users-id'),
    # sa.UniqueConstraint('username')
    # )
    pass
    # ### end Alembic commands ###
