"""empty message

Revision ID: 6f1c7d6a2d96
Revises: 153e10b8b2f7
Create Date: 2025-01-14 21:05:34.472061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1c7d6a2d96'
down_revision = '153e10b8b2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hasMessages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasMessages', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
