"""empty message

Revision ID: b19e6e749cdf
Revises: 0e363a1014d1
Create Date: 2025-01-14 21:00:36.038965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19e6e749cdf'
down_revision = '0e363a1014d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('hasMessages', sa.Boolean(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_column('hasMessages')
    pass
    # ### end Alembic commands ###
