"""adding  ondelete='CASCADE' to fks on referral and comment models

Revision ID: fd6aeb4a4ec8
Revises: 5397c398e5ff
Create Date: 2024-08-31 19:18:47.723183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6aeb4a4ec8'
down_revision = '5397c398e5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        # batch_op.drop_constraint('delete-cascade-referral-fk-on-comments', type_='foreignkey')
        batch_op.create_foreign_key('delete-cascade-referral-fk-on-comments', 'referrals', ['referral_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        # batch_op.drop_constraint('delete-cascade-shortlist-fk-on-referrals', type_='foreignkey')
        batch_op.create_foreign_key('delete-cascade-shortlist-fk-on-referrals', 'shortlists', ['shortlist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint('delete-cascade-shortlist-fk-on-referrals', type_='foreignkey')
        # batch_op.create_foreign_key('delete-cascade-shortlist-fk-on-referrals', 'shortlists', ['shortlist_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('delete-cascade-referral-fk-on-comments', type_='foreignkey')
        # batch_op.create_foreign_key('delete-cascade-referral-fk-on-comments', 'referrals', ['referral_id'], ['id'])

    # ### end Alembic commands ###
